#!/usr/bin/env bash

function display_info {
  local domain="$1"
  local subdomain="$2"

  if [ -z "$subdomain" ]; then
    subdomains=(www lb-01 web-01 web-02)
  else
    subdomains=("$subdomain")
  fi

  for subdomain in "${subdomains[@]}"; do
    dig_output=$(dig +short "$subdomain.$domain")
    record_type=$(echo "$dig_output" | grep -o 'IN \w*')
    destination=$(echo "$dig_output" | grep -o '[0-9\.]*$')
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
  done
}

domain="$1"
subdomain="$2"

display_info "$domain" "$subdomain"

