#!/bin/bash
# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

sudo sed -i '/location \/ {/a \    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;' /etc/nginx/sites-available/default

sudo systemctl restart nginx

