#!/usr/bin/env bash

# Install Nginx web server
sudo apt-get update
sudo apt-get install -y nginx

# Configure Nginx to redirect /redirect_me
sudo sed -i '/listen \[::\]:80 default_server;/a \\
        location /redirect_me { \\
            return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; \\
        }' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart

