#!/usr/bin/env bash

# Install Nginx web server
sudo apt-get update
sudo apt-get install -y nginx

# Create custom 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

# Configure Nginx to use the custom 404 error page
sudo sed -i '/# pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000/a \\
        error_page 404 /custom_404.html; \\
        location = /custom_404.html { \\
            internal; \\
        }' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart

