#!/usr/bin/env bash
# install nginx
sudo apt-get update
sudo apt-get install -y nginx

sudo sh -c 'echo "<html><body><h1>Ceci n'"'"'est pas une page</h1></body></html>" > /usr/share/nginx/html/404.html'
sudo sh -c 'echo "error_page 404 /404.html;" > /etc/nginx/conf.d/custom.conf'                                                                                                    sudo service nginx restart

