#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
# Requirements:
# Configure HAproxy so that it send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm
# Make sure that HAproxy can be managed via an init script

# Install HAproxy
apt-get -y update
apt-get install -y haproxy

# Load balancing configuration
printf %s "
frontend talenthive.tech
    bind *:80
    mode http
    default_backend talenthive-backend
backend talenthive-backend
    balance roundrobin
    option forwardfor
    server 141899-web-01 54.166.138.104:80 check
    server 141899-web-02 100.25.198.209:80 check
" >> /etc/haproxy/haproxy.cfg

printf %s "
ENABLED=1
" >> /etc/default/haproxy

service haproxy restart
