#!/usr/bin/env bash
# This script creates the file /var/run/myscript.pid containing its PID,
# displays "To infinity and beyond" indefinitely,
# displays "I hate the kill command" when receiving a SIGTERM signal,
# displays "Y U no love me?!" when receiving a SIGINT signal,
# and deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

# Create the file /var/run/myscript.pid containing the script's PID
echo $$ > /var/run/myscript.pid

# Set signal handlers
trap 'echo "I hate the kill command"; exit 0' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm /var/run/myscript.pid; echo "Goodbye cruel world"; exit 0' SIGQUIT SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done

