#!/usr/bin/env bash
# This script kills the 7-highlander process

# Get the process ID of the 7-highlander script
pid=$(pgrep -f "7-highlander")

# Use the pkill command to stop the process
pkill -f "7-highlander"

