#!/bin/bash

# Loop through numbers 1 to 100
for i in {1..100}; do
    # Initialize output as the current number
    output=$i
    # Check if the number is a multiple of 3 and 5
    if [ $(($i % 3)) -eq 0 ] && [ $(($i % 5)) -eq 0 ]; then
        output="FizzBuzz"
    # Check if the number is a multiple of 3
    elif [ $(($i % 3)) -eq 0 ]; then
        output="Fizz"
    # Check if the number is a multiple of 5
    elif [ $(($i % 5)) -eq 0 ]; then
        output="Buzz"
    fi
    # Display the output in list format
    echo "- $output"
done

