#!/usr/bin/env bash
# This script uses a while loop to display "Best School" 10 times. On the 9th iteration, it also displays "Hi" on a new line.

counter=1
while [ $counter -le 10 ]
do
  if [ $counter -eq 9 ]; then
    echo "Best School"
    echo "Hi"
  else
    echo "Best School"
  fi
  counter=$((counter + 1))
done

