#!/usr/bin/env bash
# This script is displaying numbers from 1 to 20 and displaying different messages for the 4th, 9th, and 17th loop iteration

count=1

while [ $count -le 20 ]
do
  case $count in
    4)
      echo "4 bad luck from China"
      ;;
    9)
      echo "9 bad luck from Japan"
      ;;
    17)
      echo "17 bad luck from Italy"
      ;;
    *)
      echo $count
      ;;
  esac
  ((count++))
done

