#!/usr/bin/env bash
# This script is displaying hours and minutes in a clock format

hour=0
while [ $hour -lt 13 ]
do
  echo "Hour: $hour"
  minute=1
  while [ $minute -lt 60 ]
  do
    echo "$minute"
    minute=$((minute + 1))
  done
  hour=$((hour + 1))
done

