#!/usr/bin/env bash
# This script configures an Ubuntu server by mapping localhost to 127.0.0.2 and facebook.com to 8.8.8.8 in the /etc/hosts file 

cp /etc/hosts ~/hosts.new
sed -i 's/^127.0.0.1.*$/127.0.0.2 localhost/' ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
echo ""
